name: "Index.html updater"

on:
  push:
    branch:
      - main

jobs:
  generate-index-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        run: |
          cd scripts/
          chmod -x index-update.sh
          ./index-update.sh
        shell:  bash